<?php

namespace ErrorHandlerModule;

/**
 * Výchozí chybová stránka aplikace
 * @var bool $logged byla chyba úspěšně zalogována?
 */

// Načtení názvu souboru chyby.
$errorFile = (isset($exception) && $exception instanceof \Throwable)
    ? ErrorHandler::getErrorFile($exception)
    : 'no code';

?>
<!DOCTYPE html><!-- "' --></textarea></script></style></pre></xmp></a></audio></button></canvas></datalist></details></dialog></iframe></listing></meter></noembed></noframes></noscript></optgroup></option></progress></rp></select></table></template></title></video>
<meta charset="utf-8">
<meta name=robots content=noindex>
<meta name=generator content="Tracy">

<title>Server Error</title>

<style>
	#tracy-error { all: initial; position: absolute; top: 0; left: 0; right: 0; height: 70vh; min-height: 400px; display: flex; align-items: center; justify-content: center; z-index: 1000 }
	#tracy-error div { all: initial; max-width: 550px; background: white; color: #333; display: block }
	#tracy-error h1 { all: initial; font: bold 50px/1.1 sans-serif; display: block; margin: 40px }
	#tracy-error p { all: initial; font: 20px/1.4 sans-serif; margin: 40px; display: block }
	#tracy-error small { color: gray }
	#tracy-error small span { color: silver; font-size: 90%; }
</style>

<div id=tracy-error>
	<div>
		<h1>Server Error</h1>

		<p>We're sorry! The server encountered an internal error and
		was unable to complete your request. Please try again later.</p>

		<p>
            <small>error 500
                <?php if ($logged) : ?>
                <span> | <?php echo $errorFile ?></span>
                <?php else: ?>
                <span> | <?php echo @date('j. n. Y H:i') ?><br>Tracy is unable to log error.</span>
                <?php endif; ?>
            </small>
        </p>
	</div>
</div>

<script>
	document.body.insertBefore(document.getElementById('tracy-error'), document.body.firstChild);
</script>
